---
title: "Case Studies"
---


Below is a list of the case studies that were created last summer. Many of the case studies are still drafts, so please keep that in mind. The goal of the case studies is to allow students to grapple with more complex problems, often drawing upon skills acquired through multiple tutorials. Further, we hope that the case studies better equip students to ask their own questions.

You can download all of the materials for a topic by selecting *zip* (note: Mac users need to use Chrome or Firefox for the zip file to download). You can preview the tutorials as html documents. If you're a [GitHub](https://github.com/) user, please feel free to fork the [repository](https://github.com/ds4stats/case-studies)!

<br>

**NYPD Stop and Frisk**

This case study combines data collected from the 2015 records of the New York Police Department that resulted in an arrest with information from the 2010 census. It has students exam either the effectiveness of the Stop-and-frisk policy or the relationship between education quality and crime.

[html](https://rawgit.com/ds4stats/case-studies/master/NYPD%20Stop%20and%20Frisk_CaseStudy/NYPD2015.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/case-studies/tree/master/NYPD%20Stop%20and%20Frisk_CaseStudy) | [github](https://github.com/ds4stats/case-studies/tree/master/NYPD%20Stop%20and%20Frisk_CaseStudy)


**Terrorism**

This case study examines the extent to which CBRN weapons have been used so far and challenges students to examine whether or not their past use fits with our perceptions.

[html](https://rawgit.com/ds4stats/case-studies/master/Terrorism_CaseStudy/CBRN_events.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/case-studies/tree/master/Terrorism_CaseStudy) |  [github](https://github.com/ds4stats/case-studies/tree/master/Terrorism_CaseStudy)


**Baseball Salaries**

Explores how team payroll is related to team success using Sean Lahman's database. A SQLite version of the database was created so students can see how to work with SQL via `dplyr`.

[html](https://rawgit.com/ds4stats/case-studies/master/baseball-salaries/WrangleRelationalData.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/case-studies/tree/master/baseball-salaries) |  [github](https://github.com/ds4stats/case-studies/tree/master/baseball-salaries)


**Oklahoma Earthquakes**

The number of earthquakes in Oklahoma has increased in the past decade. In fact, scientists now claim that Oklahoma surpasses California in being the "earthquake capital of the world!" This case study examines how the distribution of earthquakes in Oklahoma has changed over time.

[html](https://rawgit.com/ds4stats/case-studies/master/ok-earthquakes/OKEarthquakes.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/case-studies/tree/master/ok-earthquakes) |  [github](https://github.com/ds4stats/case-studies/tree/master/ok-earthquakes)


**Texas Tornadoes**

This case study has students exam the distribution of tornadoes in Texas from 2011 to 2015. In which months do tornadoes tend to occur? What time? Is there a pattern to where the strongest tornadoes occur?

[html](https://rawgit.com/ds4stats/case-studies/master/tx-tornadoes/TxTornadoes.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/case-studies/tree/master/tx-tornadoes) |  [github](https://github.com/ds4stats/case-studies/tree/master/tx-tornadoes)


**Twitter Sentiment Analysis**

This case study allows students to practice manipulating text data using regular expressions. Specifically, it has students explore tweets.

[html](https://rawgit.com/ds4stats/case-studies/master/twitter-sentiment/Love.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/case-studies/tree/master/twitter-sentiment) |  [github](https://github.com/ds4stats/case-studies/tree/master/twitter-sentiment)



