---
title: "Modules for Infusing Data Science into the Statistics Curriculum"
---

* * * 

## Overview

This workshop will explore ways to incorporate data-scientific topics into existing statistics courses, especially at the introductory level. It will preview modules that allow for the inclusion of introductory tutorials and lab activities into courses for students with limited technical backgrounds. Participants will work through class-tested tutorials and lab activities. Key topics will include data wrangling and statistical graphics. The workshop will close with a discussion related to how these materials have been used in existing courses and an overview of the supporting materials. Basic knowledge of R will be valuable, but not required.

The tutorials and case studies were developed by [Adam Loy](https://aloy.github.io/), [Shonda Kuiper](https://www.grinnell.edu/users/kuipers), and [Laura Chihara](http://www.people.carleton.edu/~lchihara/) with support from the [ACM FaCE program](http://www.acm.edu/professional_development/FaCE__Faculty_Career_Enhancement_Project_.html) and [The Teagle Foundation](http://hybridliberalarts.org/about/). 

Special thanks for [Ivan Ramler](https://www.stlawu.edu/people/ivan-ramler) for helping with the workshop!

* * * 


## Preparation

Prior to the workshop, please do the following:

1. Make sure that you have access to R and RStudio. I set up an RStudio server for today's workshop: [http://bit.ly/ds4stats-rstudio](http://bit.ly/ds4stats-rstudio)
1. If using your own computer, update/install your R packages using the below code:

    ```{r eval=FALSE}
    update.packages()
    install.packages(c("mosaic", "tidyverse", "rmarkdown"))
    ```
    
1. If you have never seen R Studio or R markdown before, then please read the following:
    - [R and RStudio Basics](https://ismayc.github.io/rbasics-book/3-rstudiobasics.html) by Chester Ismay
    - [R markdown](https://ismayc.github.io/rbasics-book/4-rmarkdown.html) by Chester Ismay


* * *


## Outline


### Welcome!

1. Introductions
1. Open [communal notes](https://docs.google.com/document/d/1_AruRpFzSMv_Io5eoh_CiBmV4l0I11WFU61FpnA5BJg/edit?usp=sharing) -- Add questions, comments, and notes throughout the workshop
1. Brief overview of the project

### Data visualization with `ggplot2`

##### Workflow

1. Download the [zip file](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/worksop/tree/master/intro_ggplot2) containing the module. (Note: Mac users will need to use Chrome or Firefox, the download does not work with Safari.) 
1. Upload the zip file to the R Studio server OR unzip and store in a logical location on your laptop.
1. Plot data with `ggplot2`!

#####  Additional resources

- My [`ggplot2 cheatsheet for Intro Stats`](assets/refcard/m107-EDA-refcard.pdf)
- R Studio's [`ggplot2` cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf)

#####  If you get done early...

Check out another tutorial related to statistical graphics

- [Shonda's version](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/data-viz) of intro to `ggplot2`
- [Intro to maps with `ggplot2`](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/intro-maps)
- [Making maps with shapefiles](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/maps-shapefiles)

### Data wrangling with `dplyr`


##### Workflow

1. Download the [zip file](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/worksop/tree/master/intro_dplyr) containing the module.  (Note: Mac users will need to use Chrome or Firefox, the download does not work with Safari.)
1. Upload the zip file to the R Studio server OR unzip and store in a logical location on your laptop.
1. Wrangle data with `dplyr`!


#####  Additional resources

- R Studio's [Data wrangling cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)


#####  If you get done early...

Check out another tutorial/exercise related to data wrangling

- [Tidy data with `tidyr`](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/tidying-data)
- [Merging data with `dplyr`](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/merging)
- [Ivan's `dplyr` and `ggplot2` practice problems](http://myslu.stlawu.edu/~iramler/stat201/dplyr_ggplot_tasks.html)

### Wrapping up

1. Pull files off the RStudio server
1. What topics/materials are missing?
1. How might you incorporate these modules into your classes?

* * *

## Additional Resources

1. Check out the [Tutorials](tutorials.html) and [Case studies](case-studies.html) tabs of the website
1. [Full list of tutorials on Stat2Labs](http://web.grinnell.edu/individuals/kuipers/stat2labs/RTutorials.html)
1. ds4stats [GitHub organization](https://github.com/ds4stats)
1. My [Fall 2016 intro stats materials](http://math107-lu.github.io/)
1. [rawgit](https://rawgit.com/) for displaying .html versions of the tutorials directly from GitHub
1. [DownGit](https://minhaskamal.github.io/DownGit/#/home) for downloading .zip files for specific folders on GitHub