---
title: "Tutorials"
---

Below is the complete list of tutorials that were created last summer. We wrote the materials so that they would be accessible to an introductory student in a class setting or a more-advanced student outside of class. You can download all of the materials for a topic by selecting *zip* (note: Mac users need to use Chrome or Firefox for the zip file to download). You can preview the tutorials as html documents. If you're a [GitHub](https://github.com/) user, please feel free to fork the [repository](https://github.com/ds4stats/r-tutorials)!


**Tidy Data with `tidyr`** 

[html](https://cdn.rawgit.com/ds4stats/r-tutorials/e9e5efc2/tidying-data/IntroTidyData.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/tidying-data) |  [github](https://github.com/ds4stats/r-tutorials/tree/master/tidying-data)


**Data Wrangling: An Introduction to `dplyr`**

[html](https://rawgit.com/ds4stats/r-tutorials/master/data-wrangling/IntroDplyr.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/data-wrangling) |  [github](https://github.com/ds4stats/r-tutorials/tree/master/data-wrangling)


**Merging Data with `dplyr`**

[html](https://rawgit.com/ds4stats/r-tutorials/master/merging/IntroMerging.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/merging) |  [github](https://github.com/ds4stats/r-tutorials/tree/master/merging)


**Data Visualization: An Introduction to `ggplot2`**

[html](https://cdn.rawgit.com/ds4stats/r-tutorials/e9e5efc2/data-viz/IntroToGgplot.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/data-viz) |  [github](https://github.com/ds4stats/r-tutorials/tree/master/data-viz)


**Introduction to Creating Maps with `ggplot2`**

[html](https://rawgit.com/ds4stats/r-tutorials/master/intro-maps/IntroMakingMaps.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/intro-maps) |  [github](https://github.com/ds4stats/r-tutorials/tree/master/intro-maps)


**Making Maps with Shapefiles**

[html](https://rawgit.com/ds4stats/r-tutorials/master/maps-shapefiles/MakingMapsWithShapefiles.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/maps-shapefiles) |  [github](https://github.com/ds4stats/r-tutorials/tree/master/maps-shapefiles)


**Manipulating Text**

[html](https://rawgit.com/ds4stats/r-tutorials/master/manipulating-text/IntroStrings.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/manipulating-text) |  [github](https://github.com/ds4stats/r-tutorials/tree/master/manipulating-text)


**Working with Dates and Times**

[html](https://rawgit.com/ds4stats/r-tutorials/master/dates-times/IntroDates.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/dates-times) |  [github](https://github.com/ds4stats/r-tutorials/tree/master/dates-times)


**Introduction to Data Scraping with `rvest`**

[html](https://rawgit.com/ds4stats/r-tutorials/master/data-scraping/IntroDataScraping.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/ds4stats/r-tutorials/tree/master/data-scraping) |  [github](https://github.com/ds4stats/r-tutorials/tree/master/data-scraping)


* * * 

### Labs for Intro Stats

This Fall, I adapted the visualization and data wrangling labs for use in my introductory statistics course. I also created additional labs to continue to introduce students to R. Below are the set of labs I used in class.

Here is the [full schedule](http://math107-lu.github.io/) for my class.

**Lab 1: Creating Graphs with ggplot2**

[html](https://cdn.rawgit.com/aloy/m107/766262ec/labs/01-ggplot2/01-IntroToGgplot.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/aloy/m107/tree/master/labs/01-ggplot2) |  [github](https://github.com/aloy/m107/tree/master/labs/01-ggplot2)


**Lab 2: Introduction to Data Manipulation in R**

[html](https://cdn.rawgit.com/aloy/m107/766262ec/labs/02-dplyr/02-IntroDplyr.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/aloy/m107/tree/master/labs/02-dplyr) |  [github](https://github.com/aloy/m107/tree/master/labs/02-dplyr)


**Lab 3: Introduction to Hypothesis Testing**

[html](https://cdn.rawgit.com/aloy/m107/d1b98730/labs/03-permutationTests/03-permutationTests.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/aloy/m107/tree/master/labs/03-permutationTests) |  [github](https://github.com/aloy/m107/tree/master/labs/03-permutationTests)


**Lab 4: Comparing Two Proportions**

[html](https://cdn.rawgit.com/aloy/m107/d1b98730/labs/04-permutationTests2/04-permutationTests2.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/aloy/m107/tree/master/labs/04-permutationTests2) |  [github](https://github.com/aloy/m107/tree/master/labs/04-permutationTests2)


**Lab 5A: The one-sample bootstrap**

[html](https://cdn.rawgit.com/aloy/m107/d1b98730/labs/05-oneSampleBootstrap/lab5.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/aloy/m107/tree/master/labs/05-oneSampleBootstrap) |  [github](https://github.com/aloy/m107/tree/master/labs/05-oneSampleBootstrap)


**Lab 5B: The two-sample bootstrap**

[html](https://cdn.rawgit.com/aloy/m107/d1b98730/labs/05B-twoSampleBootstrap/lab5b.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/aloy/m107/tree/master/labs/05B-twoSampleBootstrap) | [github](https://github.com/aloy/m107/tree/master/labs/05B-twoSampleBootstrap)


**Lab 6: Simple linear regression in R**

[html](https://cdn.rawgit.com/aloy/m107/ec1cffc0/labs/06-slr/lab6.html) | [zip](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/aloy/m107/tree/master/labs/06-slr) | [github](https://github.com/aloy/m107/tree/master/labs/06-slr)

